language: php
php:
    - '5.6'
    - '7.0'
    - '7.1'
before_script: 
    - ./mongo-installer.sh
    - phpenv config-add travisConfig.ini
    - composer self-update
    - composer install --prefer-source --no-interaction
    
script: phpunit